[available_vision_models."mistralai/mistral-small-3.2-24b-instruct:free"]
provider = "Mistral"
model_name_short = "Mistral Small 3.2 24B (free)"
display_name = "Mistral: Mistral Small 3.2 24B (free)"
created = "2025-06-20T18:10:16Z"
modality = "text+image->text"
input_modalities = [ "image", "text",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."mistralai/mistral-small-3.2-24b-instruct"]
provider = "Mistral"
model_name_short = "Mistral Small 3.2 24B"
display_name = "Mistral: Mistral Small 3.2 24B"
created = "2025-06-20T18:10:16Z"
modality = "text+image->text"
input_modalities = [ "image", "text",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-flash-lite-preview-06-17"]
provider = "Google"
model_name_short = "Gemini 2.5 Flash Lite Preview 06-17"
display_name = "Google: Gemini 2.5 Flash Lite Preview 06-17"
created = "2025-06-17T15:23:51Z"
modality = "text+image->text"
input_modalities = [ "file", "image", "text",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-flash"]
provider = "Google"
model_name_short = "Gemini 2.5 Flash"
display_name = "Google: Gemini 2.5 Flash"
created = "2025-06-17T15:01:28Z"
modality = "text+image->text"
input_modalities = [ "file", "image", "text",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-pro"]
provider = "Google"
model_name_short = "Gemini 2.5 Pro"
display_name = "Google: Gemini 2.5 Pro"
created = "2025-06-17T14:12:24Z"
modality = "text+image->text"
input_modalities = [ "file", "image", "text",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/o3-pro"]
provider = "OpenAI"
model_name_short = "o3 Pro"
display_name = "OpenAI: o3 Pro"
created = "2025-06-10T23:32:32Z"
modality = "text+image->text"
input_modalities = [ "text", "file", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-pro-preview"]
provider = "Google"
model_name_short = "Gemini 2.5 Pro Preview 06-05"
display_name = "Google: Gemini 2.5 Pro Preview 06-05"
created = "2025-06-05T15:27:37Z"
modality = "text+image->text"
input_modalities = [ "file", "image", "text",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-flash-preview-05-20"]
provider = "Google"
model_name_short = "Gemini 2.5 Flash Preview 05-20"
display_name = "Google: Gemini 2.5 Flash Preview 05-20"
created = "2025-05-20T17:25:24Z"
modality = "text+image->text"
input_modalities = [ "image", "text", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-flash-preview-05-20:thinking"]
provider = "Google"
model_name_short = "Gemini 2.5 Flash Preview 05-20 (thinking)"
display_name = "Google: Gemini 2.5 Flash Preview 05-20 (thinking)"
created = "2025-05-20T17:25:24Z"
modality = "text+image->text"
input_modalities = [ "image", "text", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/codex-mini"]
provider = "OpenAI"
model_name_short = "Codex Mini"
display_name = "OpenAI: Codex Mini"
created = "2025-05-16T15:36:01Z"
modality = "text+image->text"
input_modalities = [ "image", "text",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."mistralai/mistral-medium-3"]
provider = "Mistral"
model_name_short = "Mistral Medium 3"
display_name = "Mistral: Mistral Medium 3"
created = "2025-05-07T14:15:41Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-pro-preview-05-06"]
provider = "Google"
model_name_short = "Gemini 2.5 Pro Preview 05-06"
display_name = "Google: Gemini 2.5 Pro Preview 05-06"
created = "2025-05-07T00:41:53Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-flash-preview"]
provider = "Google"
model_name_short = "Gemini 2.5 Flash Preview 04-17"
display_name = "Google: Gemini 2.5 Flash Preview 04-17"
created = "2025-04-17T18:31:07Z"
modality = "text+image->text"
input_modalities = [ "image", "text", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-flash-preview:thinking"]
provider = "Google"
model_name_short = "Gemini 2.5 Flash Preview 04-17 (thinking)"
display_name = "Google: Gemini 2.5 Flash Preview 04-17 (thinking)"
created = "2025-04-17T18:31:07Z"
modality = "text+image->text"
input_modalities = [ "image", "text", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/o4-mini-high"]
provider = "OpenAI"
model_name_short = "o4 Mini High"
display_name = "OpenAI: o4 Mini High"
created = "2025-04-16T17:23:32Z"
modality = "text+image->text"
input_modalities = [ "image", "text", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/o3"]
provider = "OpenAI"
model_name_short = "o3"
display_name = "OpenAI: o3"
created = "2025-04-16T17:10:57Z"
modality = "text+image->text"
input_modalities = [ "image", "text", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/o4-mini"]
provider = "OpenAI"
model_name_short = "o4 Mini"
display_name = "OpenAI: o4 Mini"
created = "2025-04-16T16:29:02Z"
modality = "text+image->text"
input_modalities = [ "image", "text",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4.1"]
provider = "OpenAI"
model_name_short = "GPT-4.1"
display_name = "OpenAI: GPT-4.1"
created = "2025-04-14T17:23:05Z"
modality = "text+image->text"
input_modalities = [ "image", "text", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4.1-mini"]
provider = "OpenAI"
model_name_short = "GPT-4.1 Mini"
display_name = "OpenAI: GPT-4.1 Mini"
created = "2025-04-14T17:23:01Z"
modality = "text+image->text"
input_modalities = [ "image", "text", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4.1-nano"]
provider = "OpenAI"
model_name_short = "GPT-4.1 Nano"
display_name = "OpenAI: GPT-4.1 Nano"
created = "2025-04-14T17:22:49Z"
modality = "text+image->text"
input_modalities = [ "image", "text", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."meta-llama/llama-4-maverick:free"]
provider = "Meta"
model_name_short = "Llama 4 Maverick (free)"
display_name = "Meta: Llama 4 Maverick (free)"
created = "2025-04-05T19:37:02Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."meta-llama/llama-4-maverick"]
provider = "Meta"
model_name_short = "Llama 4 Maverick"
display_name = "Meta: Llama 4 Maverick"
created = "2025-04-05T19:37:02Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."meta-llama/llama-4-scout:free"]
provider = "Meta"
model_name_short = "Llama 4 Scout (free)"
display_name = "Meta: Llama 4 Scout (free)"
created = "2025-04-05T19:31:59Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."meta-llama/llama-4-scout"]
provider = "Meta"
model_name_short = "Llama 4 Scout"
display_name = "Meta: Llama 4 Scout"
created = "2025-04-05T19:31:59Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.5-pro-exp-03-25"]
provider = "Google"
model_name_short = "Gemini 2.5 Pro Experimental"
display_name = "Google: Gemini 2.5 Pro Experimental"
created = "2025-03-25T17:01:39Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."mistralai/mistral-small-3.1-24b-instruct"]
provider = "Mistral"
model_name_short = "Mistral Small 3.1 24B"
display_name = "Mistral: Mistral Small 3.1 24B"
created = "2025-03-17T19:15:37Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4.5-preview"]
provider = "OpenAI"
model_name_short = "GPT-4.5 (Preview)"
display_name = "OpenAI: GPT-4.5 (Preview)"
created = "2025-02-27T20:23:30Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.0-flash-lite-001"]
provider = "Google"
model_name_short = "Gemini 2.0 Flash Lite"
display_name = "Google: Gemini 2.0 Flash Lite"
created = "2025-02-25T17:56:52Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-2.0-flash-001"]
provider = "Google"
model_name_short = "Gemini 2.0 Flash"
display_name = "Google: Gemini 2.0 Flash"
created = "2025-02-05T15:30:13Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/o1"]
provider = "OpenAI"
model_name_short = "o1"
display_name = "OpenAI: o1"
created = "2024-12-17T18:26:39Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4o-2024-11-20"]
provider = "OpenAI"
model_name_short = "GPT-4o (2024-11-20)"
display_name = "OpenAI: GPT-4o (2024-11-20)"
created = "2024-11-20T18:33:14Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."mistralai/pixtral-large-2411"]
provider = "Mistral"
model_name_short = "Pixtral Large 2411"
display_name = "Mistral: Pixtral Large 2411"
created = "2024-11-19T00:49:48Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-flash-1.5-8b"]
provider = "Google"
model_name_short = "Gemini 1.5 Flash 8B"
display_name = "Google: Gemini 1.5 Flash 8B"
created = "2024-10-03T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."mistralai/pixtral-12b"]
provider = "Mistral"
model_name_short = "Pixtral 12B"
display_name = "Mistral: Pixtral 12B"
created = "2024-09-10T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4o-2024-08-06"]
provider = "OpenAI"
model_name_short = "GPT-4o (2024-08-06)"
display_name = "OpenAI: GPT-4o (2024-08-06)"
created = "2024-08-06T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4o-mini"]
provider = "OpenAI"
model_name_short = "GPT-4o-mini"
display_name = "OpenAI: GPT-4o-mini"
created = "2024-07-18T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4o-mini-2024-07-18"]
provider = "OpenAI"
model_name_short = "GPT-4o-mini (2024-07-18)"
display_name = "OpenAI: GPT-4o-mini (2024-07-18)"
created = "2024-07-18T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-flash-1.5"]
provider = "Google"
model_name_short = "Gemini 1.5 Flash"
display_name = "Google: Gemini 1.5 Flash "
created = "2024-05-14T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4o"]
provider = "OpenAI"
model_name_short = "GPT-4o"
display_name = "OpenAI: GPT-4o"
created = "2024-05-13T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4o:extended"]
provider = "OpenAI"
model_name_short = "GPT-4o (extended)"
display_name = "OpenAI: GPT-4o (extended)"
created = "2024-05-13T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."openai/gpt-4o-2024-05-13"]
provider = "OpenAI"
model_name_short = "GPT-4o (2024-05-13)"
display_name = "OpenAI: GPT-4o (2024-05-13)"
created = "2024-05-13T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image", "file",]
last_seen = "2025-06-24T07:36:29+00:00Z"

[available_vision_models."google/gemini-pro-1.5"]
provider = "Google"
model_name_short = "Gemini 1.5 Pro"
display_name = "Google: Gemini 1.5 Pro"
created = "2024-04-09T00:00:00Z"
modality = "text+image->text"
input_modalities = [ "text", "image",]
last_seen = "2025-06-24T07:36:29+00:00Z"
